version: "3"

services:
  swecommerce:
    container_name: swecommerce
    restart: always
    build: ./swEcommerce/.
    ports:
      - "3000:3001"
    links:
      - pg
    depends_on:
      - pg
    # volumes:
    #   - "./swEcommerce/:/usr/src/app/"

  swetracking:
    container_name: swdelivery
    restart: always
    build: ./swDelivery/.
    ports:
      - "4000:3002"
    links:
      - pg
    depends_on:
      - pg
    # volumes:
    #   - "./swDelivery/:/usr/src/app/"
  pg:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enviamedb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "80:80"
    depends_on:
      - pg
