version: "3"

services:
  api:
    container_name: backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - pg
  pg:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= enviamedb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "80:80"
    depends_on:
      - pg
