
###agregar vendedores
POST http://localhost:3000/admin/newseller
Content-Type: application/json

{
    "name": "vendedor 2",
    "short_description": "Perez",
    "email": "luis2@nomail.com",
    "password": "123456",
    "wharehouse": "Calle falsa 123"
}


### listar vendedor por id
GET http://localhost:3000/admin/seller/3
Content-Type: application/json


### editar vendedor por id
PUT http://localhost:3000/admin/seller/2
Content-Type: application/json

{
    "wharehouse": "Otra Calle falsa 123"
}


### listar vendedores
GET http://localhost:3000/admin/sellers/
Content-Type: application/json


### eliminar vendedor por id
PUT http://localhost:3000/admin/seller/2
Content-Type: application/json


### Cancelar pedidos 

PUT http://localhost:3000/marketplace/cancel/order/2/state/5
Content-Type: application/json


### listar Order todas las ordenes 
 http://localhost:3000/admin/orders
Content-Type: application/json