
### listar todos los productos con su respectivos vendedores
GET http://localhost:3001/marketplace/products/
Content-Type: application/json

### comprar un producto
GET http://localhost:3001/marketplace/products/buy/9/quality/2/calle1/1
Content-Type: application/json


### cancelar order
PUT http://localhost:3001/marketplace/cancel/order/2/state/5
Content-Type: application/json






