###agregar Productos
POST http://localhost:3001/seller/newproduct
Content-Type: application/json

{
    "name": "chompas",
    "short_description": "chompas de cuero",
    "idSeller": 1,
    "stock": 24
}

### listar Productos por vendedores
GET http://localhost:3001/sellers/1/products
Content-Type: application/json

### listar producto por id del usuario y por id del producto
GET http://localhost:3001/seller/1/product/1
Content-Type: application/json


### editar producto  por el vendedor y por el id del producto
PUT http://localhost:3001/seller/1/product/5
Content-Type: application/json

{
    "name": "chompa americana",
    "short_description": "chompas de cuero"
}


### eliminar producto por vendedor y  por id del producto
DELETE  http://localhost:3001/seller/1/product/6
Content-Type: application/json
